// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using cp_randomcard.Infra.Data;

#nullable disable

namespace cp_randomcard.Migrations
{
    [DbContext(typeof(CardContext))]
    [Migration("20240524023901_CreatingCardTable")]
    partial class CreatingCardTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cp_randomcard.Entities.Card", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CARD_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Atribute")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("CARD_ATRIBUTE");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CARD_HEALTH");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CARD_POWER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("CARD_TITLE");

                    b.HasKey("Id");

                    b.ToTable("CARD", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
